[project]
name = "datastar-zd"
version = "0.3.0"
description = "simple website using datastar-py"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "datastar-py>=1.0.0",
    "fastapi[all]>=0.136.1",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.28",
]

[dependency-groups]
dev = [
    "ruff>=0.15.13",
    "ty>=0.0.37",
]

[tool.fastapi]
entrypoint = "main:app"
